SELECT * FROM `employees` WHERE `last_name` LIKE 'K%';
SELECT * FROM `employees` WHERE `last_name` LIKE '%i';
SELECT concat(`first_name`, ' ', `middle_name`, ' ', `last_name`) AS `full_name`  , `hire_date`  FROM `employees` WHERE `hire_date` BETWEEN '2015-01-01' AND '2015-03-31' ORDER BY `hire_date` ASC;
SELECT `e1`.`last_name` AS `Employee`, `e2`.`last_name` AS `Boss` FROM `employees` AS `e1`, `employees` AS `e2` WHERE `e1`.`boss_id` = `e2`.`id`;
SELECT `last_name` FROM `employees` WHERE `department_id` = 3 ORDER BY `last_name` DESC;
SELECT COUNT(`middle_name`) AS `count_has_middle` FROM `employees`;
SELECT `d`.`name`, (SELECT COUNT(*) FROM `employees` WHERE `d`.`id` = `employees`.`department_id`) AS `department_count` FROM `departments` AS `d` WHERE NOT (SELECT COUNT(*) FROM `employees` WHERE `d`.`id` = `employees`.`department_id`) = 0;
SELECT `first_name`, `middle_name`, `last_name`, `hire_date`  FROM `employees` ORDER BY `hire_date` DESC LIMIT 1;
SELECT `d`.`name`, (SELECT COUNT(*) FROM `employees` WHERE `d`.`id` = `employees`.`department_id`) AS `department_count` FROM `departments` AS `d` WHERE (SELECT COUNT(*) FROM `employees` WHERE `d`.`id` = `employees`.`department_id`) = 0;
SELECT `e`.`first_name`, `e`.`middle_name`, `e`.`last_name` FROM `employees` AS `e` WHERE (SELECT COUNT(*) FROM `employee_positions` AS `ep` WHERE `e`.`id` =  `ep`.`employee_id`) > 1;
